"""
main.py
-------
Entry point for the Solace AI FastAPI application.

Run the development server with:
    python -m uvicorn main:app --reload

API Docs (auto-generated by FastAPI):
    Swagger UI → http://127.0.0.1:8000/docs
    ReDoc      → http://127.0.0.1:8000/redoc
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from routes.chat import router as chat_router

# ---------------------------------------------------------------------------
# Application factory
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Solace AI",
    description=(
        "An empathetic mental wellness chatbot powered by FastAPI. "
        "Solace AI detects your emotional state and responds with care, "
        "while prioritising your safety above all else."
    ),
    version="1.0.0",
    contact={
        "name": "Solace AI Support",
        "email": "support@solaceai.example.com",
    },
    license_info={
        "name": "MIT",
    },
)

# ---------------------------------------------------------------------------
# CORS middleware — allow frontend clients to call the API
# Restrict `allow_origins` to your frontend domain in production.
# ---------------------------------------------------------------------------

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],       # e.g. ["https://solaceai.example.com"] in prod
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Register routers
# ---------------------------------------------------------------------------

app.include_router(chat_router)

# ---------------------------------------------------------------------------
# Root health-check endpoint
# ---------------------------------------------------------------------------

@app.get("/", tags=["Health"], summary="Health check")
async def root() -> dict:
    """Returns a simple status message to confirm the API is running."""
    return {
        "status": "ok",
        "app": "Solace AI",
        "version": "1.0.0",
        "message": "Welcome to Solace AI — your mental wellness companion. 💙",
    }
