"""
chat_schema.py
--------------
Pydantic schemas for validating request and response bodies
for the /chat endpoint.
"""

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Schema for incoming user message."""
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The user's message to the chatbot.",
        example="I've been feeling really sad lately."
    )


class ChatResponse(BaseModel):
    """Schema for the structured chatbot response."""
    reply: str = Field(
        ...,
        description="The empathetic response generated by Solace AI."
    )
    emotion: str = Field(
        ...,
        description="The detected emotion of the user's message."
    )
    safe: bool = Field(
        ...,
        description="Whether the message was flagged as safe (True) or a crisis (False)."
    )
